require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - Gemfile
    - config/environment.rb
    - config/initializers/**/*
    - db/migrate/*.rb
    - db/schema.rb
    - bin/*
    - tmp/**/*
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - bin/*

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false